//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySwoleMate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySwoleMateEntities : DbContext
    {
        public MySwoleMateEntities()
            : base("name=MySwoleMateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
    }
}
