//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySwoleMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int MeasurementID { get; set; }
        public int Weight { get; set; }
        public int Waist { get; set; }
        public int BodyFat { get; set; }
        public int Chest { get; set; }
        public int UpperArm { get; set; }
        public int ScheduleID { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
